### ISSUE TITLE
New subcommand: Read a config on runtime from YAML

### ISSUE THREAD

**Issue by drewsortega** [OSU-SOC/nagini#3]
Currently, basic configuration is provided globally/per user in /etc/nagini/config.yaml and ~/.config/nagini/config.yaml.

As an alternative to `nagini run`, add something along the lines of `nagini play`:

`nagini play local_config.yaml`

Where local_config.yaml looks something like:

```yaml
threads: 6
concat: true
outdir: all_local_dns/
log_type: dns
command: grepcidr 10.0.0.0/24

time_range:
  start_time: 2021/05/12:00
  end_time: 2021/06/10:11
```
